### ISSUE TITLE
Class Naming - Organization

### ISSUE THREAD

**Issue by winnuayi** [ciheul/baros#1]
Penamaan class di `core/models.py` dan `rest/api.py` antara `Organization` dan `CallCenter` harus dibenahi.

`OrganizationAbstract` menjadi `AbstractOrganization` agar konsisten dengan penamaan di Django.

Di `core/models.py`, model `Organization` diubah menjadi `CallCenter`.

Di `rest/api.py`, class `OrganizationListApi` menjadi `PoliceOfficeListApi` dan class `OrganizationApi` menjadi `PoliceOfficeApi`.

**Comment by DyvannoPC** [comment]
Pembuatan API ini didasari dari mockup-requirement untuk call center yang menampilkan informasi damkar/rs maupun kantor polisi. Sehingga tiga hal ini digabung menjadi satu kesatuan dalam `CallCenterApi`.

Saran penamaan `core.model.py`:
1. `OrganizationAbstract` --> `AbstractOrganization`
2. `Organization` --> `CallCenter`
akan di develop lebih lanjut.

**Comment by DyvannoPC** [comment]
perubahan `core.model.py`:
1. `OrganizationAbstract` --> `AbstractOrganization`
2. `Organization` --> `CallCenter`
(**_implemented_**)
