### ISSUE TITLE
Peran Account CustomUser pada Fitur Baru

### ISSUE THREAD

**Issue by DyvannoPC** [ciheul/baros#5]
Apakah setiap fitur **Complaints, Lost, SKCK** tersebut perlu untuk mencantumkan foreign key `user_id`  (acuan kepada table `CustomUser` pada modul Account) pada `core/models.py` ?

**Comment by winnuayi** [comment]
Iya, @DyvannoPC . Biar ketika ditampilkan complaint, lost, skck, kelihatan siapa yang create.
